// GENERATED by scripts/generate-style-profiles.ts — do not edit by hand.
// Regenerate: npm run generate:style-profiles
import type { BeatStyleId } from "./beatStyles";
import type { NormalizationStats, StyleFeatureVector } from "./styleFidelity";

export const STYLE_PROFILE_STATS: NormalizationStats = {
  "mean": {
    "bpmNorm": 0.57125,
    "swing": 0.08000000000000002,
    "onsetDensity": 0.244140625,
    "laneShareKick": 0.2630126173276328,
    "laneShareSnare": 0.11691975035628285,
    "laneShareHat": 0.48218401395645977,
    "laneShareOpenHat": 0.13788361835962454,
    "syncopation": 0.5814121701312104,
    "backbeat": 0.75,
    "rmsNorm": 0.09478772497518272,
    "lowEnergyShare": 0.6190490190801891,
    "zcr": 0.2242785336807422
  },
  "std": {
    "bpmNorm": 0.10936607106411018,
    "swing": 0.06,
    "onsetDensity": 0.033088035832221516,
    "laneShareKick": 0.02708214817019288,
    "laneShareSnare": 0.038494778046541035,
    "laneShareHat": 0.09068177417233719,
    "laneShareOpenHat": 0.06705503700738612,
    "syncopation": 0.13409045565652097,
    "backbeat": 0.4330127018922193,
    "rmsNorm": 0.011983547439335092,
    "lowEnergyShare": 0.043682630110382106,
    "zcr": 0.06439050830463834
  }
};

export const STYLE_GOLDENS: Record<BeatStyleId, StyleFeatureVector> = {
  "afrobeats": {
    "bpmNorm": 0.52,
    "swing": 0.1,
    "onsetDensity": 0.265625,
    "laneShareKick": 0.29411764705882354,
    "laneShareSnare": 0.11764705882352941,
    "laneShareHat": 0.47058823529411764,
    "laneShareOpenHat": 0.11764705882352941,
    "syncopation": 0.7647058823529411,
    "backbeat": 1,
    "rmsNorm": 0.09754302511949096,
    "lowEnergyShare": 0.6465451517287489,
    "zcr": 0.2350508803101276
  },
  "amapiano": {
    "bpmNorm": 0.56,
    "swing": 0.14,
    "onsetDensity": 0.234375,
    "laneShareKick": 0.26666666666666666,
    "laneShareSnare": 0.13333333333333333,
    "laneShareHat": 0.4,
    "laneShareOpenHat": 0.2,
    "syncopation": 0.6,
    "backbeat": 1,
    "rmsNorm": 0.09508238397233088,
    "lowEnergyShare": 0.5785291308185356,
    "zcr": 0.2781810381810382
  },
  "crunk": {
    "bpmNorm": 0.48,
    "swing": 0.04,
    "onsetDensity": 0.234375,
    "laneShareKick": 0.26666666666666666,
    "laneShareSnare": 0.13333333333333333,
    "laneShareHat": 0.5333333333333333,
    "laneShareOpenHat": 0.06666666666666667,
    "syncopation": 0.5333333333333333,
    "backbeat": 1,
    "rmsNorm": 0.08920825999210912,
    "lowEnergyShare": 0.6639536392606369,
    "zcr": 0.19792894935752078
  },
  "drill": {
    "bpmNorm": 0.72,
    "swing": 0.12,
    "onsetDensity": 0.28125,
    "laneShareKick": 0.2777777777777778,
    "laneShareSnare": 0.05555555555555555,
    "laneShareHat": 0.5555555555555556,
    "laneShareOpenHat": 0.1111111111111111,
    "syncopation": 0.6666666666666666,
    "backbeat": 0,
    "rmsNorm": 0.1086457982759151,
    "lowEnergyShare": 0.6599889652274933,
    "zcr": 0.16815974547890153
  },
  "house": {
    "bpmNorm": 0.62,
    "swing": 0,
    "onsetDensity": 0.21875,
    "laneShareKick": 0.2857142857142857,
    "laneShareSnare": 0.14285714285714285,
    "laneShareHat": 0.2857142857142857,
    "laneShareOpenHat": 0.2857142857142857,
    "syncopation": 0.2857142857142857,
    "backbeat": 1,
    "rmsNorm": 0.08773260232686968,
    "lowEnergyShare": 0.5498855831931158,
    "zcr": 0.30970336852689795
  },
  "pop": {
    "bpmNorm": 0.59,
    "swing": 0.02,
    "onsetDensity": 0.234375,
    "laneShareKick": 0.2,
    "laneShareSnare": 0.13333333333333333,
    "laneShareHat": 0.5333333333333333,
    "laneShareOpenHat": 0.13333333333333333,
    "syncopation": 0.5333333333333333,
    "backbeat": 1,
    "rmsNorm": 0.09291800035604693,
    "lowEnergyShare": 0.5656183364285021,
    "zcr": 0.30871798543124584
  },
  "rnb": {
    "bpmNorm": 0.37,
    "swing": 0.18,
    "onsetDensity": 0.1875,
    "laneShareKick": 0.25,
    "laneShareSnare": 0.16666666666666666,
    "laneShareHat": 0.5,
    "laneShareOpenHat": 0.08333333333333333,
    "syncopation": 0.5833333333333334,
    "backbeat": 1,
    "rmsNorm": 0.07282738968466503,
    "lowEnergyShare": 0.6317318860959896,
    "zcr": 0.1357176607421946
  },
  "trap": {
    "bpmNorm": 0.71,
    "swing": 0.04,
    "onsetDensity": 0.296875,
    "laneShareKick": 0.2631578947368421,
    "laneShareSnare": 0.05263157894736842,
    "laneShareHat": 0.5789473684210527,
    "laneShareOpenHat": 0.10526315789473684,
    "syncopation": 0.6842105263157895,
    "backbeat": 0,
    "rmsNorm": 0.11434434007403396,
    "lowEnergyShare": 0.6561394598884903,
    "zcr": 0.1607686414180109
  }
};
