// GENERATED by scripts/generate-style-profiles.ts — do not edit by hand.
// Regenerate: npm run generate:style-profiles
import type { BeatStyleId } from "./beatStyles";
import type { NormalizationStats, StyleFeatureVector } from "./styleFidelity";

export const STYLE_PROFILE_STATS: NormalizationStats = {
  "mean": {
    "bpmNorm": 0.5642857142857143,
    "swing": 0.09142857142857144,
    "onsetDensity": 0.24776785714285715,
    "laneShareKick": 0.25976952184382524,
    "laneShareSnare": 0.11321440857044572,
    "laneShareHat": 0.510251117991056,
    "laneShareOpenHat": 0.11676495159467296,
    "syncopation": 0.623654725047914,
    "backbeat": 0.7142857142857143,
    "rmsNorm": 0.09579559963922743,
    "lowEnergyShare": 0.6289295099211996,
    "zcr": 0.21207498584557707
  },
  "std": {
    "bpmNorm": 0.1152459658862783,
    "swing": 0.055402055513329475,
    "onsetDensity": 0.03385212251808728,
    "laneShareKick": 0.027460497785367067,
    "laneShareSnare": 0.03979577913876025,
    "laneShareHat": 0.05564014855501167,
    "laneShareOpenHat": 0.039632474225180916,
    "syncopation": 0.07920473417985228,
    "backbeat": 0.4517539514526256,
    "rmsNorm": 0.012489754880899411,
    "lowEnergyShare": 0.03741357245775798,
    "zcr": 0.05955694994947329
  }
};

export const STYLE_GOLDENS: Record<BeatStyleId, StyleFeatureVector> = {
  "afrobeats": {
    "bpmNorm": 0.52,
    "swing": 0.1,
    "onsetDensity": 0.265625,
    "laneShareKick": 0.29411764705882354,
    "laneShareSnare": 0.11764705882352941,
    "laneShareHat": 0.47058823529411764,
    "laneShareOpenHat": 0.11764705882352941,
    "syncopation": 0.7647058823529411,
    "backbeat": 1,
    "rmsNorm": 0.09754302511949096,
    "lowEnergyShare": 0.6465451517287489,
    "zcr": 0.2350508803101276
  },
  "amapiano": {
    "bpmNorm": 0.56,
    "swing": 0.14,
    "onsetDensity": 0.234375,
    "laneShareKick": 0.26666666666666666,
    "laneShareSnare": 0.13333333333333333,
    "laneShareHat": 0.4,
    "laneShareOpenHat": 0.2,
    "syncopation": 0.6,
    "backbeat": 1,
    "rmsNorm": 0.09508238397233088,
    "lowEnergyShare": 0.5785291308185356,
    "zcr": 0.2781810381810382
  },
  "crunk": {
    "bpmNorm": 0.48,
    "swing": 0.04,
    "onsetDensity": 0.234375,
    "laneShareKick": 0.26666666666666666,
    "laneShareSnare": 0.13333333333333333,
    "laneShareHat": 0.5333333333333333,
    "laneShareOpenHat": 0.06666666666666667,
    "syncopation": 0.5333333333333333,
    "backbeat": 1,
    "rmsNorm": 0.08920825999210912,
    "lowEnergyShare": 0.6639536392606369,
    "zcr": 0.19792894935752078
  },
  "drill": {
    "bpmNorm": 0.72,
    "swing": 0.12,
    "onsetDensity": 0.28125,
    "laneShareKick": 0.2777777777777778,
    "laneShareSnare": 0.05555555555555555,
    "laneShareHat": 0.5555555555555556,
    "laneShareOpenHat": 0.1111111111111111,
    "syncopation": 0.6666666666666666,
    "backbeat": 0,
    "rmsNorm": 0.1086457982759151,
    "lowEnergyShare": 0.6599889652274933,
    "zcr": 0.16815974547890153
  },
  "pop": {
    "bpmNorm": 0.59,
    "swing": 0.02,
    "onsetDensity": 0.234375,
    "laneShareKick": 0.2,
    "laneShareSnare": 0.13333333333333333,
    "laneShareHat": 0.5333333333333333,
    "laneShareOpenHat": 0.13333333333333333,
    "syncopation": 0.5333333333333333,
    "backbeat": 1,
    "rmsNorm": 0.09291800035604693,
    "lowEnergyShare": 0.5656183364285021,
    "zcr": 0.30871798543124584
  },
  "rnb": {
    "bpmNorm": 0.37,
    "swing": 0.18,
    "onsetDensity": 0.1875,
    "laneShareKick": 0.25,
    "laneShareSnare": 0.16666666666666666,
    "laneShareHat": 0.5,
    "laneShareOpenHat": 0.08333333333333333,
    "syncopation": 0.5833333333333334,
    "backbeat": 1,
    "rmsNorm": 0.07282738968466503,
    "lowEnergyShare": 0.6317318860959896,
    "zcr": 0.1357176607421946
  },
  "trap": {
    "bpmNorm": 0.71,
    "swing": 0.04,
    "onsetDensity": 0.296875,
    "laneShareKick": 0.2631578947368421,
    "laneShareSnare": 0.05263157894736842,
    "laneShareHat": 0.5789473684210527,
    "laneShareOpenHat": 0.10526315789473684,
    "syncopation": 0.6842105263157895,
    "backbeat": 0,
    "rmsNorm": 0.11434434007403396,
    "lowEnergyShare": 0.6561394598884903,
    "zcr": 0.1607686414180109
  }
};
