// GENERATED by scripts/generate-style-profiles.ts — do not edit by hand.
// Regenerate: npm run generate:style-profiles
import type { BeatStyleId } from "./beatStyles";
import type { NormalizationStats, StyleFeatureVector } from "./styleFidelity";

export const STYLE_PROFILE_STATS: NormalizationStats = {
  "mean": {
    "bpmNorm": 0.5622222222222222,
    "swing": 0.07777777777777778,
    "onsetDensity": 0.22395833333333334,
    "laneShareKick": 0.22170322319961122,
    "laneShareSnare": 0.12420157146679335,
    "laneShareHat": 0.43094719369229173,
    "laneShareOpenHat": 0.11203690053019259,
    "syncopation": 0.5320154962569822,
    "backbeat": 0.5555555555555556,
    "rmsNorm": 0.0819375564844949,
    "lowEnergyShare": 0.5406109293355017,
    "zcr": 0.20906654912725886
  },
  "std": {
    "bpmNorm": 0.1062259413574855,
    "swing": 0.05691665988829199,
    "onsetDensity": 0.08652733190539662,
    "laneShareKick": 0.08864498557091505,
    "laneShareSnare": 0.08454292032939893,
    "laneShareHat": 0.173731217899583,
    "laneShareOpenHat": 0.07162874212547332,
    "syncopation": 0.2318368173161242,
    "backbeat": 0.4969039949999533,
    "rmsNorm": 0.03174624561045512,
    "lowEnergyShare": 0.19936193881094802,
    "zcr": 0.10458380556919296
  }
};

export const STYLE_GOLDENS: Record<BeatStyleId, StyleFeatureVector> = {
  "afrobeats": {
    "bpmNorm": 0.52,
    "swing": 0.1,
    "onsetDensity": 0.265625,
    "laneShareKick": 0.29411764705882354,
    "laneShareSnare": 0.11764705882352941,
    "laneShareHat": 0.47058823529411764,
    "laneShareOpenHat": 0.11764705882352941,
    "syncopation": 0.7647058823529411,
    "backbeat": 1,
    "rmsNorm": 0.09754302511949096,
    "lowEnergyShare": 0.6465451517287489,
    "zcr": 0.2350508803101276
  },
  "amapiano": {
    "bpmNorm": 0.56,
    "swing": 0.14,
    "onsetDensity": 0,
    "laneShareKick": 0,
    "laneShareSnare": 0,
    "laneShareHat": 0,
    "laneShareOpenHat": 0,
    "syncopation": 0,
    "backbeat": 0,
    "rmsNorm": 0,
    "lowEnergyShare": 0,
    "zcr": 0
  },
  "bounce": {
    "bpmNorm": 0.49,
    "swing": 0.06,
    "onsetDensity": 0.296875,
    "laneShareKick": 0.15789473684210525,
    "laneShareSnare": 0.3157894736842105,
    "laneShareHat": 0.42105263157894735,
    "laneShareOpenHat": 0.10526315789473684,
    "syncopation": 0.7368421052631579,
    "backbeat": 0,
    "rmsNorm": 0.07421859253132326,
    "lowEnergyShare": 0.49163534219653865,
    "zcr": 0.3655517108804306
  },
  "crunk": {
    "bpmNorm": 0.48,
    "swing": 0.04,
    "onsetDensity": 0.234375,
    "laneShareKick": 0.26666666666666666,
    "laneShareSnare": 0.13333333333333333,
    "laneShareHat": 0.5333333333333333,
    "laneShareOpenHat": 0.06666666666666667,
    "syncopation": 0.5333333333333333,
    "backbeat": 1,
    "rmsNorm": 0.08920825999210912,
    "lowEnergyShare": 0.6639536392606369,
    "zcr": 0.19792894935752078
  },
  "drill": {
    "bpmNorm": 0.72,
    "swing": 0.12,
    "onsetDensity": 0.28125,
    "laneShareKick": 0.2777777777777778,
    "laneShareSnare": 0.05555555555555555,
    "laneShareHat": 0.5555555555555556,
    "laneShareOpenHat": 0.1111111111111111,
    "syncopation": 0.6666666666666666,
    "backbeat": 0,
    "rmsNorm": 0.1086457982759151,
    "lowEnergyShare": 0.6599889652274933,
    "zcr": 0.16815974547890153
  },
  "house": {
    "bpmNorm": 0.62,
    "swing": 0,
    "onsetDensity": 0.21875,
    "laneShareKick": 0.2857142857142857,
    "laneShareSnare": 0.14285714285714285,
    "laneShareHat": 0.2857142857142857,
    "laneShareOpenHat": 0.2857142857142857,
    "syncopation": 0.2857142857142857,
    "backbeat": 1,
    "rmsNorm": 0.08773260232686968,
    "lowEnergyShare": 0.5498855831931158,
    "zcr": 0.30970336852689795
  },
  "pop": {
    "bpmNorm": 0.59,
    "swing": 0.02,
    "onsetDensity": 0.234375,
    "laneShareKick": 0.2,
    "laneShareSnare": 0.13333333333333333,
    "laneShareHat": 0.5333333333333333,
    "laneShareOpenHat": 0.13333333333333333,
    "syncopation": 0.5333333333333333,
    "backbeat": 1,
    "rmsNorm": 0.09291800035604693,
    "lowEnergyShare": 0.5656183364285021,
    "zcr": 0.30871798543124584
  },
  "rnb": {
    "bpmNorm": 0.37,
    "swing": 0.18,
    "onsetDensity": 0.1875,
    "laneShareKick": 0.25,
    "laneShareSnare": 0.16666666666666666,
    "laneShareHat": 0.5,
    "laneShareOpenHat": 0.08333333333333333,
    "syncopation": 0.5833333333333334,
    "backbeat": 1,
    "rmsNorm": 0.07282738968466503,
    "lowEnergyShare": 0.6317318860959896,
    "zcr": 0.1357176607421946
  },
  "trap": {
    "bpmNorm": 0.71,
    "swing": 0.04,
    "onsetDensity": 0.296875,
    "laneShareKick": 0.2631578947368421,
    "laneShareSnare": 0.05263157894736842,
    "laneShareHat": 0.5789473684210527,
    "laneShareOpenHat": 0.10526315789473684,
    "syncopation": 0.6842105263157895,
    "backbeat": 0,
    "rmsNorm": 0.11434434007403396,
    "lowEnergyShare": 0.6561394598884903,
    "zcr": 0.1607686414180109
  }
};
