import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { BEAT_STYLES, type BeatStyleId } from "../src/lib/beatStyles";
import { loadKitFromDisk } from "../src/lib/loadKit.node";
import { renderPatternToPcm } from "../src/lib/styleRender";
import {
  computeNormalizationStats,
  extractStyleFeatures,
  FIDELITY_DRUM_LANES,
  type StyleFeatureVector,
} from "../src/lib/styleFidelity";

function main(): void {
  const kit = loadKitFromDisk();
  const ids = (Object.keys(BEAT_STYLES) as BeatStyleId[]).sort();
  const goldens = {} as Record<BeatStyleId, StyleFeatureVector>;
  for (const id of ids) {
    const style = BEAT_STYLES[id];
    goldens[id] = extractStyleFeatures(
      style.pattern, style, renderPatternToPcm(style.pattern, style, kit, FIDELITY_DRUM_LANES),
    );
  }
  const stats = computeNormalizationStats(ids.map((id) => goldens[id]));

  const banner =
    "// GENERATED by scripts/generate-style-profiles.ts — do not edit by hand.\n" +
    "// Regenerate: npm run generate:style-profiles\n";
  const body =
    `import type { BeatStyleId } from "./beatStyles";\n` +
    `import type { NormalizationStats, StyleFeatureVector } from "./styleFidelity";\n\n` +
    `export const STYLE_PROFILE_STATS: NormalizationStats = ${JSON.stringify(stats, null, 2)};\n\n` +
    `export const STYLE_GOLDENS: Record<BeatStyleId, StyleFeatureVector> = ${JSON.stringify(goldens, null, 2)};\n`;

  writeFileSync(join(process.cwd(), "src/lib/styleProfiles.generated.ts"), banner + body);
  console.log(`Wrote style profiles for ${ids.length} genres.`);
}

main();
